modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/itssimple/.mod-issue-tracker"
logoFile="icon.png"

[[mods]]
modId="mobpacifier"
version="1.0"
displayName="Mob Pacifier"
displayURL=""
authors="NoLifeKing85"
description="Finally a way to lure mobs away from you in a safe way!"


[[dependencies.mobpacifier]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"